[package]
name = "mlog_parse"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"
# subenum = "1.1.3"

[dependencies.strum]
version = "0.27.2"
features = ["derive"]

[dev-dependencies]
pretty_assertions = "1.4.1"
